export const TOTALSCORE = 'TOTALSCORE';
export const MATCHINGITEM = 'MATCHINGITEM';
export const ISFIRSTINSTALL = 'ISFIRSTINSTALL';
export const NOTIFICATIONCOUNT = 'NOTIFICATIONCOUNT';
export const MESSAGECOUNT = 'MESSAGECOUNT';
export const REMEMBERME = 'REMEMBERME';
export const ITEMUPLODED = 'ITEMUPLODED';
export const ISDARKTHEME = 'ISDARKTHEME';
export const FAVIROTCATEGORY = 'FAVIROTCATEGORY';
export const ALLOWSWIPERIGHT = 'ALLOWSWIPERIGHT';
export const ISSHOWPOPUPAGAIN = 'ISSHOWPOPUPAGAIN';
export const ISSHOWFIRSTPOPUPAGAIN = 'ISSHOWFIRSTPOPUPAGAIN';



