const Images = {

  // Botoom Tab Images
  homeactive: require('../Images/BottomTab/homeactive.png'),
  homeinactive: require('../Images/BottomTab/homeinactive.png'),
  listactive: require('../Images/BottomTab/listactive.png'),
  listinactive: require('../Images/BottomTab/listinactive.png'),
  additemactive: require('../Images/BottomTab/additemactive.png'),
  additeminactive: require('../Images/BottomTab/additeminactive.png'),
  messageactive: require('../Images/BottomTab/messageactive.png'),
  notification: require('../Images/BottomTab/notification.png'),
  messageinactive: require('../Images/BottomTab/messageinactive.png'),
  profileactive: require('../Images/BottomTab/profileactive.png'),
  profileinactive: require('../Images/BottomTab/profileinactive.png'),
  logoColor: require('../Images/logoColor.png'),
  HeaderBackarow: require('../Images/HeaderBackarow.png'),
  logoSimple: require('../Images/logoSimple.png'),
  logoBranding: require('../Images/logoBranding.png'),
  switcherooround: require('../Images/switcherooround.png'),
  // facebookIcon: require('../Images/facebookIcon.png'),
  facebookIcon: require('../Images/facebook_new_logo.png'),
  // googleIcon: require('../Images/googleIcon.png'),
  googleIcon: require('../Images/google_new_logo.png'),
  appleLogin: require('../Images/appleLogin.png'),
  showFirst: require('../Images/showFirst.png'),
  test2: require('../Images/test2.png'),
  testProduct: require('../Images/testProduct.png'),
  Deletebtn: require('../Images/Deletebtn.png'),
  BackGroundDesing: require('../Images/BackGroundDesing.png'),
  itsAmatch: require('../Images/itsAmatch.png'),
  Share: require('../Images/Share.png'),
  Copy: require('../Images/Copy.png'),
  Newupdate: require('../Images/Newupdate.png'),
  SwitchWith: require('../Images/SwitchWith.png'),
  verticaldot: require('../Images/verticaldot.png'),
  togolon: require('../Images/togolon.png'),
  togoloff: require('../Images/togoloff.png'),
  rightarrow: require('../Images/rightarrow.png'),
  addProfilePic: require('../Images/addProfilePic.png'),
  close: require('../Images/close.png'),
  swipeCircleTick: require('../Images/swipeCircleTick.png'),
  Emptydata: require('../Images/Emptydata.png'),
  swipeCircleCross: require('../Images/swipeCircleCross.png'),
  addphoto: require('../Images/addphoto.png'),
  verifayEmail: require('../Images/verifayEmail.png'),
  welcome: require('../Images/welcome.png'),
  passshow: require('../Images/passshow.png'),
  passhide: require('../Images/passhide.png'),
  tickcheck: require('../Images/tickcheck.png'),
  location: require('../Images/location.png'),
  tick: require('../Images/tick.png'),
  radioactive: require('../Images/radioactive.png'),
  radioinactive: require('../Images/radioinactive.png'),
  emptyitem: require('../Images/emptyitem.png'),
  calander: require('../Images/calander.png'),
  activeCheck: require('../Images/activeCheck.png'),
  unactivecheck: require('../Images/unactivecheck.png'),
  checkbox: require('../Images/checkbox.png'),
  uncheckbox: require('../Images/uncheckbox.png'),
  DolorSign: require('../Images/DolorSign.png'),
  Adminlogo: require('../Images/Adminlogo.jpg'),
  EmptyNotification: require('../Images/EmptyNotification.png'),
  feedback: require('../Images/feedback.png'),
  // male: require('../Images/male.png'),
  // female: require('../Images/female.png'),
  // other: require('../Images/other.png'),
  male: require('../Images/male_2.png'),
  female: require('../Images/female_2.png'),
  other: require('../Images/other_2.png'),
  matchSwap: require('../Images/match_swap.png'),
  emptyListImage: require('../Images/empty_list.jpg'),
  arrowUp: require('../Images/arrow_up.png'),
  arrowDown: require('../Images/arrow_down.png'),
};
export default Images;

